### PR TITLE
Add support for sidecar containers

### PR DESCRIPTION
**Pull request by hajali-amine**
This PR is to solve #19

Basically adding support for sidecar containers. An example usecase would be;

``` yaml
# values.yaml
sidecarContainers:
  - name: my-sidecar
    image: hajali-amine/my-sidecar-image
    imagePullPolicy: Always
    ports:
    - name: my-port
      containerPort: 5000
      protocol: TCP
    resources:
      requests:
        memory: 10Mi
        cpu: 10m
      limits:
        memory: 100Mi
        cpu: 100m
```

### CODE REVIEW

**Review by fabriziobonavita — APPROVED** [review]
Thank you @hajali-amine for the contribution!

**Comment by hajali-amine** [comment]
Hello 😄 
Any updates concerning this PR? Should I make more changes? 
cc @fabriziobonavita @M-Nawar

**Comment by fabriziobonavita** [comment]
It is approved, we wanted to leave the honour of merging to you @hajali-amine

**Comment by fabriziobonavita** [comment]
My fault :D

**Pull request merged**
