### PR TITLE
chore: add cm checksum annotations to reload pods on cm change

### PR DESCRIPTION
**Pull request by cyril-corbon**
add checksum annotations to reload pods on configmap update

### CODE REVIEW

**Comment by fabriziobonavita** [comment]
Hi @cyril-corbon 
thank you very much for the contribution.
Not all our users might actually want a restart on configmap change. What do you think about making this optional?

**Comment by cyril-corbon** [comment]
> Hi @cyril-corbon thank you very much for the contribution. Not all our users might actually want a restart on configmap change. What do you think about making this optional?

as you wish, but it's seems not right to have a config that is not applied in pods

**Comment by fabriziobonavita** [comment]
Yes thank you, that would be perfect.

**Comment by fabriziobonavita** [comment]
Thank you so much for the contribution @cyril-corbon

**Pull request merged**
