### PR TITLE
Added support for reading apiKey and readOnlyApiKey from external secrets.

### PR DESCRIPTION
**Pull request by NathanSavageKaimai**
Added support for reading apiKey and readOnlyApiKey from external secrets. Also added support for the valueFrom convention in container secrets.

### CODE REVIEW

**Comment by bashofmann** [comment]
Thanks. I'll have a look.

**Comment by bashofmann** [comment]
Looks better now. @NathanSavageKaimai Could you also add a bats integration test that verify that configuring the api key through a secret works?

**Comment by NathanSavageKaimai** [comment]
thanks, I will try. :)

**Comment by bashofmann** [comment]
It should be rather straight forward. If it takes you too much time, I can also take this over next week.

**Comment by NathanSavageKaimai** [comment]
should be good to test again

**Review by bashofmann — APPROVED** [review]

**Comment by freinold** [comment]
I noticed this is not yet included because there was no release built since then.
@bashofmann when do you plan to release a new chart version?

**Comment by NathanSavageKaimai** [comment]
> I noticed this is not yet included because there was no Release built since the merge. @bashofmann when do you plan to release a new Chart version?

it was included in version 1.11.4 :)

**Pull request merged**
