### PR TITLE
support a generic ingress

### PR DESCRIPTION
**Pull request by M-Nawar**

### CODE REVIEW

**Comment by M-Nawar** [comment]
closes #32

**Comment by M-Nawar** [comment]
Hi @Nastaliss thanks for your feedback, regarding the service name targeting Qdrant by default i updated that. Imho it is intended that the ingress is disabled by default, as this is not meant to work out of the box, it has to be configured either ways, also for backward compatibility as well

**Comment by Nastaliss** [comment]
I fully agree that the ingress should be disabled by default. 
I was just thinking that the resouce should be configured to work with minimal configuration from the user's end. 

I think that instead of ranging on `ingress.hosts[].paths`, 
```
{{- range .paths }}
- path: {{ .path | quote }}
  pathType: {{ .pathType | default "Prefix" | quote }}
  backend:
    service:
      name: {{ default .serviceName (include "qdrant.fullname" $) }}
      port:
        number: {{ .servicePort }}
{{- end }}
```
I would rather hard code the whole service configuration in the ingress. 
As the `ingress.hosts` is a list it is not possible to amend the host part in this config :
```
- host: example-domain.com
  paths:
    - path: /
      pathType: Prefix
      servicePort: 6333
```
without having to redefine the `paths`.

**Comment by M-Nawar** [comment]
Hi @Nastaliss thanks for your explanation. We reconsidered your suggestion but still think that the way how we provide defaults in the values.yaml is user-friendly enough especially when it comes to any additional customizations for the paths.
Let me know if we missed a way of how you would want to use the helm chart differently.

**Pull request merged**
